french to english text translations
udem-dlteam/ribbit pull request #42
Opened 2023-04-19 13:15 UTC by bentaca

2023-04-22 21:41 UTC, leo-ard requested changes
Thanks a lot for the PR. I reviewed the content and did minor corrections as comments. I'll approve the changes once it's done !

2023-04-22 21:41 UTC, leo-ard commented on docs/lab-presentation/04.1.py
> +# ;; en: string string is replaced
Here, it should be "this string is replaced" instead of "string string is replaced"

2023-04-22 21:41 UTC, leo-ard commented on docs/lab-presentation/05.1-en.txt
> +   - Enabled or disabled the check of the number of arguments
Here it should be `Enable or disable the check for the number of arguments`

2023-04-22 21:41 UTC, leo-ard commented on docs/lab-presentation/05.1-en.txt
> +   - Enabled other components like GC, tail-call, threads...
`Enabled` -> `Enable`

2023-04-22 21:41 UTC, leo-ard commented on docs/lab-presentation/06.1.scm
> +;; fr: Now we will compile the following file with rsc
`en` and `fr` mixed up here

2023-04-22 21:41 UTC, leo-ard commented on docs/lab-presentation/08.1.c
> +//We want to develop a system that allows to show the code dependency:
This translation is better : `We developed a system that lets us show dependency between features`.

2023-04-22 21:41 UTC, leo-ard commented on docs/practical-guide-for-vm-markup-en.md
> +       box 2: // @@(primitive (arg1 x y)
The code was translated here ! It should be `case`

2023-04-22 21:41 UTC, leo-ard commented on docs/practical-guide-for-vm-markup-en.md
> +       box 2: // @@(primitive (arg1 x y)
Same here

2023-04-22 21:41 UTC, leo-ard commented on docs/practical-guide-for-vm-markup-en.md
> +box 0: // jump/call
Should be `case`

2023-04-24 10:32 UTC, bentaca commented on docs/lab-presentation/05.1-en.txt
> +   - Enabled or disabled the check of the number of arguments
fixed

2023-04-24 10:33 UTC, bentaca commented on docs/lab-presentation/06.1.scm
> +;; fr: Now we will compile the following file with rsc
fixed

2023-04-24 10:33 UTC, bentaca commented on docs/lab-presentation/08.1.c
> +//We want to develop a system that allows to show the code dependency:
fixed

2023-04-24 10:33 UTC, bentaca commented on docs/practical-guide-for-vm-markup-en.md
> +       box 2: // @@(primitive (arg1 x y)
fixed

2023-04-24 10:33 UTC, bentaca commented on docs/practical-guide-for-vm-markup-en.md
> +       box 2: // @@(primitive (arg1 x y)
fixed

2023-04-24 10:33 UTC, bentaca commented on docs/practical-guide-for-vm-markup-en.md
> +box 0: // jump/call
fixed

2023-04-24 10:47 UTC, bentaca commented
Sorry for all the annoying errors, and also messed up the commit for the spelling fixes. After another try, I hope now its all ok and that you can use this.

2023-04-26 20:37 UTC, leo-ard commented
There is just one little error that you missed (L104 in [docs/practical-guide-for-vm-markup-en.md](https://github.com/udem-dlteam/ribbit/pull/42/files/e4ccdb68cfe3444b4c880d7a89a91dd2c04d3150#diff-c96d74e0ba7997274c8b57a3ebc55e07fb95fd403618c098511b90ca56405e70)). It should be `case` and not `box`.

Thanks for taking the time to do this :)

2023-04-26 21:16 UTC, bentxt commented
I fixed the error.
Another question: did something in the git repositoriy changed with regards in rename from master to main? I had some git errors (like always ...) and in order to make some progress with git I'd like to have a rough understanding what the reason for my problems could be.

2023-04-27 20:38 UTC, leo-ard commented
I'm not aware of any change from `main` to `master`. I think the project always worked with a `main` branch

2023-04-27 20:38 UTC, merged

2023-04-27 20:38 UTC, leo-ard commented
Thanks for the translation @bentxt  !