New GC for C host
udem-dlteam/ribbit pull request #71
Opened 2024-09-17 19:48 UTC by l4haie

2024-09-26 17:58 UTC, leo-ard requested changes
Really good ! I did put some comments, but it's mostly nit picking and renaming.

The only things missing is tests ! Once you change the names for the features, you can add it to the features list (TEST_FEATURE) of the C host. Read here how to do that : https://github.com/udem-dlteam/ribbit/tree/main/src/tests#makefile-example. I would add both the mark-and-sweep algorithm with and without the DSW optimization. If the CI is too long, we can remove the mark-and-sweep algorithm without DSW.

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
> +// @@(feature mark-sweep-gc
You should rename the feature as `c/gc/mark-and-sweep` or something similar. We try to keep host-specific features under `<host>/something` and it makes sense to put the rest under`c/gc/...`

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
> +// @@(feature dsw
Same here, you should put it under `c/gc/mark-and-sweep/dsw` because it is a specific setting for the mark-and-sweep algorithm

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
> +obj *alloc;
Additional space, you should remove this change

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
>  // #define CHECK_ACCESS
You should put the warning in a more obvious place. Something like : 
```
// WARNING : the CHECK_ACCESS macro should only be used with stop and copy GC
```

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
> +
You should keep this change for the bignum/flonum PR

2024-09-26 17:58 UTC, leo-ard commented on src/host/c/rvm.c
> +    // FIXME no gain in terms of performance... remove it?
For readability, you should define the `mark` function twice. Once for DSW, once for MARK_AND_SWEEP

2024-09-26 17:59 UTC, leo-ard commented on src/host/c/rvm.c
> +  foward:
Typo : `foward` -> `forward`

2024-09-26 18:00 UTC, leo-ard commented on src/host/c/rvm.c
> +    // FIXME no gain in terms of performance... remove it?
Can you share the benchmarks you did ? (relating to the comment `FIXME no gain in terms of performance... remove it?`)

2024-09-26 18:05 UTC, leo-ard commented on src/host/c/rvm.c
> +// @@(feature dsw
In retrospect, the `mark-and-sweep` feature seems long to type. Maybe shot it to `mas` (or something else if you have an idea) ?

2024-10-06 21:00 UTC, l4haie commented on src/host/c/rvm.c
> +    // FIXME no gain in terms of performance... remove it?
I was mostly using my test suite for the bignums/flonums library. It does trigger the GC quite frequently but we should probably have dedicated benchmarks for the garbage collectors... any suggestions? would the bootstrap be enough?

2024-10-06 21:11 UTC, l4haie commented on src/host/c/rvm.c
> +// @@(feature dsw
I prefer the more descriptive name, it's pretty long but I doubt anyone (excluding us) will want to switch from one algorithm to the other very often...

2024-10-07 15:59 UTC, l4haie commented on src/host/c/rvm.c
> +// @@(feature dsw
I renamed the features `c/gc/mark-sweep` and `c/gc/mark-sweep-dsw`. I also added 
```c
#ifdef MARK_SWEEP_DSW
#define MARK_SWEEP
#endif
```
so that we can activate the `c/gc/mark-sweep-dsw` feature without having to activate the `c/gc/mark-sweep` feature along with it, making it a bit more readable and concise.

2024-10-07 19:50 UTC, leo-ard commented on src/host/c/rvm.c
> +    // FIXME no gain in terms of performance... remove it?
Probably allocation loops (loops where you just allocate a bunch of data), maybe @feeley has some ideas ?

2024-10-10 19:42 UTC, leo-ard commented on src/host/c/makefile
> +TEST_FEATURES ?= -f+ compression/lzss/2b, -e optimal, -f+ compression/lzss/2b -e optimal, -f+ c/gc/mark-sweep, -f+ c/gc/mark-sweep-dsw
I just checked at the CI and the time is too long (~25 minutes for the C host). I think we should remove the `-e optimal` and the `c/gc/mark-sweep`, giving the following : 
```c
TEST_FEATURES ?= -f+ compression/lzss/2b, -f+ compression/lzss/2b -e optimal, -f+ c/gc/mark-sweep-dsw
# Not tested for now : "-e optimal" alone and "-f+ c/gc/mark-sweep"
```

2024-10-10 19:44 UTC, leo-ard commented
@l4haie The rest looks good ! If you fix the warning of the RVM in the CI and the time it takes (see comment above) it should be ready to be merged !

2025-01-09 20:16 UTC, leo-ard commented on src/host/c/makefile
> +TEST_FEATURES ?= -f+ compression/lzss/2b, -e optimal, -f+ compression/lzss/2b -e optimal, -f+ c/gc/mark-sweep, -f+ c/gc/mark-sweep-dsw
Resolved in [227908d](https://github.com/udem-dlteam/ribbit/pull/71/commits/227908d2bba95b62724d5c523c1efb263dd5c9f6)

2025-01-09 20:17 UTC, merged